### ISSUE TITLE
cmake: Tracking issue for the main repo PRs

### ISSUE THREAD

**Issue by hebasto** [hebasto/bitcoin#267]
The CMake staging branch has been submitted to the main repository in https://github.com/bitcoin/bitcoin/pull/30454.

@fanquake suggested offline:
> Also seems like there's quite a few changes that could have been split out up front?

Therefore, this issue aims to track such upfronted PRs, which are as follows:
- [x] https://github.com/bitcoin/bitcoin/pull/30463
- [x] https://github.com/bitcoin/bitcoin/pull/30464
- [ ] https://github.com/bitcoin/bitcoin/pull/30465
- [ ] https://github.com/bitcoin/bitcoin/pull/30477
- [x] https://github.com/bitcoin/bitcoin/pull/30488
- [x] https://github.com/bitcoin/bitcoin/pull/30490
- [x] https://github.com/bitcoin/bitcoin/pull/30491
- [ ] https://github.com/bitcoin/bitcoin/pull/30508
- [x] https://github.com/bitcoin/bitcoin/pull/30513
